name = "Dynema"
uuid = "bc27e32f-14b0-4d32-98d5-b88f38cd41e7"
authors = ["Jose Alquicira-Hernandez"]
version = "1.0.0-DEV"

[deps]
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
KernelDensitySJ = "49dc5b4e-6806-4504-b2cc-a81764e7a38b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
NearestNeighborDescent = "dd2c4c9e-a32f-5b2f-b342-08c2f244fce8"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
WildBootTests = "65c2e505-86ba-4c19-93f1-95506c1443d5"

[compat]
BSplineKit = "0.17.7"
CategoricalArrays = "0.10.8"
Distances = "0.10.12"
Distributions = "0.25.118"
GLM = "1.9.0"
KernelDensitySJ = "0.2.1"
LinearAlgebra = "1.11.0"
NamedArrays = "0.10.3"
NearestNeighborDescent = "0.3.6"
Optim = "1.12.0"
PooledArrays = "1.4.3"
PrettyTables = "2.4.0"
ProgressMeter = "1.10.2"
StaticArrays = "1.9.12"
WildBootTests = "1.0.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
