name = "Dynema"
uuid = "bc27e32f-14b0-4d32-98d5-b88f38cd41e7"
version = "1.0.0-DEV"
authors = ["Jose Alquicira-Hernandez"]

[workspace]
projects = ["docs"]

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
WildBootTests = "65c2e505-86ba-4c19-93f1-95506c1443d5"

[compat]
CategoricalArrays = "0.10.8"
Distributions = "0.25.118"
Documenter = "1.16.1"
GLM = "1.9.0"
LinearAlgebra = "1.11.0"
NamedArrays = "0.10.3"
Plots = "1.41.4"
PooledArrays = "1.4.3"
PrettyTables = "2.4.0"
ProgressMeter = "1.10.2"
StableRNGs = "1.0.3"
StaticArrays = "1.9.12"
WildBootTests = "1.0.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
